export const colorsMap = [
  { label: 'Acid Green', value: '#B0BF1A' },
  { label: 'Antique Gold', value: '#A67B25' },
  { label: 'Aqua Triblend', value: '#7FB3B8' },
  { label: 'Army', value: '#4B5320' },
  { label: 'Ash', value: '#B2BEB5' },
  { label: 'Ash / Cardinal Red', value: '#B2BEB5' },
  { label: 'Asphalt', value: '#3E3E3E' },
  { label: 'Asphalt Slub', value: '#4A4A4A' },
  { label: 'Athletic Grey', value: '#A6A6A6' },
  { label: 'Athletic Grey Triblend', value: '#9C9C9C' },
  { label: 'Athletic Heather', value: '#A8AAAC' },
  { label: 'Athletic Heather/Navy', value: '#A8AAAC' },
  { label: 'Athletic Heather/Red', value: '#A8AAAC' },
  { label: 'Athletic Leather', value: '#8C6A4A' },
  { label: 'Atlantic', value: '#3D6B85' },
  { label: 'Autumn', value: '#A0522D' },
  { label: 'Baby Blue', value: '#89CFF0' },
  { label: 'Banana Cream', value: '#FAE7B5' },
  { label: 'Beige', value: '#F5F5DC' },
  { label: 'Black', value: '#000000' },
  { label: 'Black / Gradient', value: '#000000' },
  { label: 'Black / Gradient Horiz', value: '#000000' },
  { label: 'Black / Gradient Stacked', value: '#000000' },
  { label: 'Black / Red', value: '#000000' },
  { label: 'Black / Red White', value: '#000000' },
  { label: 'Black / Red White Horiz', value: '#000000' },
  { label: 'Black / Red White Stacked', value: '#000000' },
  { label: 'Black / State Outline', value: '#000000' },
  { label: 'Black / State Solid', value: '#000000' },
  { label: 'Black / White', value: '#000000' },
  { label: 'Black / White Print', value: '#000000' },
  { label: 'Black Heather', value: '#1C1C1C' },
  { label: 'Black Slub', value: '#1A1A1A' },
  { label: 'Black/White', value: '#000000' },
  { label: 'Blended Black', value: '#1F1F1F' },
  { label: 'Blended White', value: '#F5F5F5' },
  { label: 'Blue', value: '#0066CC' },
  { label: 'Blue Jean', value: '#5D8AA8' },
  { label: 'Blue Storm', value: '#3A5F7D' },
  { label: 'Blue/White', value: '#0066CC' },
  { label: 'Bone', value: '#E3DAC9' },
  { label: 'Bright Royal', value: '#1F4FCC' },
  { label: 'Burgundy', value: '#800020' },
  { label: 'Burnt Orange', value: '#CC5500' },
  { label: 'Butter', value: '#F5E6A8' },
  { label: 'Campus Gold', value: '#C9A227' },
  { label: 'Campus Orange', value: '#E86100' },
  { label: 'Campus Purple', value: '#5B2C6F' },
  { label: 'Cancun', value: '#5FB8C6' },
  { label: 'Canvas Red', value: '#B82132' },
  { label: 'Carbon', value: '#3A3A3A' },
  { label: 'Carbon Heather', value: '#4A4A4A' },
  { label: 'Cardinal', value: '#C41E3A' },
  { label: 'Cardinal Red / White', value: '#C41E3A' },
  { label: 'Cardinal/White', value: '#C41E3A' },
  { label: 'Carolina Blue', value: '#56A0D3' },
  { label: 'Charcoal', value: '#36454F' },
  { label: 'Charcoal Heather', value: '#4A5560' },
  { label: 'Charcoal Heather/White', value: '#4A5560' },
  { label: 'Charity Pink', value: '#F5B6C9' },
  { label: 'Cherry Red', value: '#D2042D' },
  { label: 'Chestnut', value: '#954535' },
  { label: 'Chrome', value: '#C0C0C0' },
  { label: 'Citrus', value: '#E4D00A' },
  { label: 'Classic Navy', value: '#1B2A49' },
  { label: 'Classic Red', value: '#C8102E' },
  { label: 'Clay', value: '#B66A50' },
  { label: 'Clear', value: '#F5F5F5' },
  { label: 'Cloud Black', value: '#2A2A2A' },
  { label: 'Coal', value: '#2C2C2C' },
  { label: 'Coal Stone', value: '#3D3D3D' },
  { label: 'Cobalt', value: '#0047AB' },
  { label: 'Columbia Blue', value: '#9BCBEB' },
  { label: 'Columbia Blue/White', value: '#9BCBEB' },
  { label: 'Cool Blue/White', value: '#5B9BD5' },
  { label: 'Cream', value: '#FFFDD0' },
  { label: 'Cream/Des Moines', value: '#FFFDD0' },
  { label: 'Cream/Kansas City', value: '#FFFDD0' },
  { label: 'Cream/Omaha', value: '#FFFDD0' },
  { label: 'Cream/Tulsa', value: '#FFFDD0' },
  { label: 'Cypress', value: '#4A6650' },
  { label: 'Dark Ash', value: '#7B8285' },
  { label: 'Dark Chocolate', value: '#3B1E0F' },
  { label: 'Dark Gray', value: '#555555' },
  { label: 'Dark Grey', value: '#555555' },
  { label: 'Dark Grey Heather', value: '#5C5C5C' },
  { label: 'Dark Heather', value: '#5C5C5C' },
  { label: 'Dark Heather Grey', value: '#5C5C5C' },
  { label: 'Dark Heather/White', value: '#5C5C5C' },
  { label: 'Dark Lavender', value: '#734F96' },
  { label: 'Dark Navy', value: '#0A1A2F' },
  { label: 'Dark Olive', value: '#556B2F' },
  { label: 'Deep Heather', value: '#6E6E6E' },
  { label: 'Deep Navy', value: '#0B1A33' },
  { label: 'Deep Navy/White', value: '#0B1A33' },
  { label: 'Deep Red', value: '#850A0A' },
  { label: 'Deep Royal', value: '#1A2F8C' },
  { label: 'Deep Royal/White', value: '#1A2F8C' },
  { label: 'Desert Pink', value: '#E5B7A5' },
  { label: 'Desert Rose', value: '#C08081' },
  { label: 'DTG Black', value: '#000000' },
  { label: 'DTG White', value: '#FFFFFF' },
  { label: 'Ecru', value: '#C2B280' },
  { label: 'Electric Blue', value: '#7DF9FF' },
  { label: 'Envy', value: '#4A7C59' },
  { label: 'Faded Black', value: '#2B2B2B' },
  { label: 'Faded Bone', value: '#D9CFBC' },
  { label: 'Faded Ecru', value: '#B5A878' },
  { label: 'Faded Eucalyptus', value: '#92A98F' },
  { label: 'Faded Grey', value: '#9A9A9A' },
  { label: 'Faded Indigo', value: '#5868A8' },
  { label: 'Faded Khaki', value: '#BDB76B' },
  { label: 'Faded Pink', value: '#E5B5B5' },
  { label: 'Faded Powder', value: '#C8D8E4' },
  { label: 'Fine Black', value: '#0A0A0A' },
  { label: 'Fine Black/White', value: '#0A0A0A' },
  { label: 'Fine Navy', value: '#152238' },
  { label: 'Fine Navy/White', value: '#152238' },
  { label: 'Fine Red/White', value: '#C8102E' },
  { label: 'Fine White', value: '#FAFAFA' },
  { label: 'Fine White/Black', value: '#FAFAFA' },
  { label: 'Fire', value: '#E25822' },
  { label: 'Fire Red', value: '#CE2029' },
  { label: 'Forest', value: '#228B22' },
  { label: 'Forest Green', value: '#228B22' },
  { label: 'French Vanilla', value: '#F3E5AB' },
  { label: 'Gardenia', value: '#F8F4E3' },
  { label: 'Garment Dyed Black', value: '#1A1A1A' },
  { label: 'Garnet', value: '#733635' },
  { label: 'Gold', value: '#D4AF37' },
  { label: 'Granite Heather', value: '#676767' },
  { label: 'Graphite', value: '#383838' },
  { label: 'Graphite / White Print', value: '#383838' },
  { label: 'Graphite Black', value: '#1C1C1C' },
  { label: 'Graphite Heather', value: '#4A4A4A' },
  { label: 'Graphite Heather / White Print', value: '#4A4A4A' },
  { label: 'Grey', value: '#808080' },
  { label: 'Grey Concrete Heather', value: '#7E7E7E' },
  { label: 'Grey Frost', value: '#B8B8B8' },
  { label: 'Grey Frost / White', value: '#B8B8B8' },
  { label: 'Grey Frost/White', value: '#B8B8B8' },
  { label: 'Grey Heather', value: '#9A9A9A' },
  { label: 'Grey Stone', value: '#A0A0A0' },
  { label: 'Grey Triblend', value: '#888888' },
  { label: 'Hazy Pink', value: '#E8B4B8' },
  { label: 'Heather Blue Lagoon', value: '#5B8FA8' },
  { label: 'Heather Charcoal', value: '#4A5560' },
  { label: 'Heather Charcoal / White Print', value: '#4A5560' },
  { label: 'Heather Charcoal/White', value: '#4A5560' },
  { label: 'Heather Cool Blue', value: '#6B8FB5' },
  { label: 'Heather Dark Grey', value: '#5C5C5C' },
  { label: 'Heather Dark Grey/White', value: '#5C5C5C' },
  { label: 'Heather Dark Navy/White', value: '#1F2D4D' },
  { label: 'Heather Deep Royal/White', value: '#1F3A8A' },
  { label: 'Heather Deep Teal', value: '#1F5F6B' },
  { label: 'Heather Dust', value: '#B8AC9C' },
  { label: 'Heather Dusty Blue', value: '#7A9CB5' },
  { label: 'Heather Forest', value: '#3A5F3A' },
  { label: 'Heather Gray', value: '#9A9A9A' },
  { label: 'Heather Grey', value: '#9A9A9A' },
  { label: 'Heather Grey/Navy', value: '#9A9A9A' },
  { label: 'Heather Grey/Red', value: '#9A9A9A' },
  { label: 'Heather Mauve', value: '#A86B7E' },
  { label: 'Heather Mustard', value: '#C9A227' },
  { label: 'Heather Navy', value: '#2C3E5C' },
  { label: 'Heather Navy/White', value: '#2C3E5C' },
  { label: 'Heather Oatmeal', value: '#D9CDB8' },
  { label: 'Heather Olive', value: '#6B7044' },
  { label: 'Heather Orchid', value: '#A875A8' },
  { label: 'Heather Red/White', value: '#B83A3A' },
  { label: 'Heather Sand Dune', value: '#C9B79C' },
  { label: 'Heather Scarlet Red/White', value: '#B82132' },
  { label: 'Heather Sunset', value: '#E8835E' },
  { label: 'Heather True Royal', value: '#2A4FB8' },
  { label: 'Heather True Royal/White', value: '#2A4FB8' },
  { label: 'Heather Yellow Gold', value: '#D4B65A' },
  { label: 'Heathered Charcoal', value: '#4A5560' },
  { label: 'Heathered Royal/White', value: '#2A4FB8' },
  { label: 'Heathered Steel', value: '#9098A0' },
  { label: 'Heavy Metal', value: '#4D4D4F' },
  { label: 'Indigo', value: '#4B0082' },
  { label: 'Indigo/White', value: '#4B0082' },
  { label: 'Ink Blue', value: '#1F2D5C' },
  { label: 'Iris', value: '#5A4FCF' },
  { label: 'Irish Green', value: '#009A44' },
  { label: 'J Navy', value: '#152238' },
  { label: 'Jade', value: '#00A86B' },
  { label: 'Jet Black', value: '#0A0A0A' },
  { label: 'Jet black', value: '#0A0A0A' },
  { label: 'Kelly', value: '#4CBB17' },
  { label: 'Kelly Green', value: '#4CBB17' },
  { label: 'Lapis', value: '#26619C' },
  { label: 'Laurel Green', value: '#A9BA9D' },
  { label: 'Lavender', value: '#B57EDC' },
  { label: 'Lavender Blue', value: '#CCCCFF' },
  { label: 'Lemon', value: '#FFF44F' },
  { label: 'Liberty', value: '#545AA7' },
  { label: 'Light Blue', value: '#ADD8E6' },
  { label: 'Light Gray', value: '#D3D3D3' },
  { label: 'Light Olive', value: '#A4AC6E' },
  { label: 'Light Orange', value: '#FFB347' },
  { label: 'Light Pink', value: '#FFB6C1' },
  { label: 'Light Steel', value: '#B0C4DE' },
  { label: 'Light Steel/Navy', value: '#B0C4DE' },
  { label: 'Light Steel/Red', value: '#B0C4DE' },
  { label: 'Lilac', value: '#C8A2C8' },
  { label: 'Lime', value: '#BFFF00' },
  { label: 'Maize Yellow', value: '#F5D03C' },
  { label: 'Maroon', value: '#800000' },
  { label: 'Maroon/Des Moines', value: '#800000' },
  { label: 'Maroon/Kansas City', value: '#800000' },
  { label: 'Maroon/Omaha', value: '#800000' },
  { label: 'Maroon/Tulsa', value: '#800000' },
  { label: 'Marshmallow', value: '#F8F4E8' },
  { label: 'Midnight Blue', value: '#191970' },
  { label: 'Midnight Navy', value: '#0A1933' },
  { label: 'Midnight Navy/White', value: '#0A1933' },
  { label: 'Military Green', value: '#4B5320' },
  { label: 'Mineral', value: '#7A8B8B' },
  { label: 'Mint', value: '#98FF98' },
  { label: 'Mushroom', value: '#A89F91' },
  { label: 'Musk', value: '#B8A99A' },
  { label: 'Mustard', value: '#FFDB58' },
  { label: 'Natural', value: '#E8DCC4' },
  { label: 'Natural/Black', value: '#E8DCC4' },
  { label: 'Navy', value: '#000080' },
  { label: 'Navy / White Print', value: '#000080' },
  { label: 'Navy Heather', value: '#1F2D4D' },
  { label: 'Navy Triblend', value: '#1B2A4E' },
  { label: 'Navy/White', value: '#000080' },
  { label: 'New Navy', value: '#0F1F44' },
  { label: 'New Navy/White', value: '#0F1F44' },
  { label: 'New Red', value: '#C8102E' },
  { label: 'New Red/White', value: '#C8102E' },
  { label: 'Oatmeal Heather', value: '#D9CDB8' },
  { label: 'Ocean Blue', value: '#4F6F8F' },
  { label: 'Off White', value: '#FAF9F6' },
  { label: 'Olive', value: '#808000' },
  { label: 'Orange', value: '#FFA500' },
  { label: 'Orchid', value: '#DA70D6' },
  { label: 'Orchid Haze', value: '#B084A8' },
  { label: 'Oxford', value: '#5C6470' },
  { label: 'Oxford Grey', value: '#5C6470' },
  { label: 'Oxford Grey/Navy', value: '#5C6470' },
  { label: 'Oxford Grey/Red', value: '#5C6470' },
  { label: 'Pale Pink', value: '#F8D6D6' },
  { label: 'Peach', value: '#FFE5B4' },
  { label: 'Petrol', value: '#1F4E5F' },
  { label: 'Pigment Black', value: '#1A1A1A' },
  { label: 'Pine', value: '#01796F' },
  { label: 'Pine Green', value: '#01796F' },
  { label: 'Pink', value: '#FFC0CB' },
  { label: 'Pistachio', value: '#93C572' },
  { label: 'Pitch Black', value: '#000000' },
  { label: 'Platinum', value: '#E5E4E2' },
  { label: 'Plum', value: '#8E4585' },
  { label: 'Powder', value: '#B0E0E6' },
  { label: 'Powder Blue', value: '#B0E0E6' },
  { label: 'Premium Heather', value: '#7E7E7E' },
  { label: 'Purple', value: '#800080' },
  { label: 'Purple Rush', value: '#6B2C91' },
  { label: 'Purple Rush/White', value: '#6B2C91' },
  { label: 'Purple/White', value: '#800080' },
  { label: 'Red', value: '#FF0000' },
  { label: 'Red/Blue Sublimated', value: '#FF0000' },
  { label: 'Red/White', value: '#FF0000' },
  { label: 'Royal', value: '#4169E1' },
  { label: 'Royal Blue/White', value: '#4169E1' },
  { label: 'Royal Frost/White', value: '#6B8FD1' },
  { label: 'Royal Purple', value: '#7851A9' },
  { label: 'Royal/White', value: '#4169E1' },
  { label: 'Safety Yellow', value: '#EED202' },
  { label: 'Sage', value: '#9CAF88' },
  { label: 'Saltwater', value: '#6EA4BF' },
  { label: 'Sand', value: '#C2B280' },
  { label: 'Sand/Black', value: '#C2B280' },
  { label: 'Sapphire', value: '#0F52BA' },
  { label: 'Scarlet/White', value: '#FF2400' },
  { label: 'Seafoam', value: '#9FE2BF' },
  { label: 'Shadow', value: '#5B5B5B' },
  { label: 'Shiitake', value: '#A08C7D' },
  { label: 'Shiraz', value: '#7C2230' },
  { label: 'Shitake', value: '#A08C7D' },
  { label: 'Silver', value: '#C0C0C0' },
  { label: 'Silver Grey', value: '#B8B8B8' },
  { label: 'Sky', value: '#87CEEB' },
  { label: 'Slate Blue', value: '#6A5ACD' },
  { label: 'Smoke', value: '#738276' },
  { label: 'Smoked Paprika', value: '#8B3A3A' },
  { label: 'Solid Black Blend', value: '#1A1A1A' },
  { label: 'Solid Black Blend/White', value: '#1A1A1A' },
  { label: 'Solid Black Triblend', value: '#1A1A1A' },
  { label: 'Solid White Blend', value: '#FAFAFA' },
  { label: 'Solid White Blend/Navy', value: '#FAFAFA' },
  { label: 'Solid White Blend/Red', value: '#FAFAFA' },
  { label: 'Solid White Triblend', value: '#FAFAFA' },
  { label: 'Sport Dark Navy', value: '#152238' },
  { label: 'Sport Dark Navy/White', value: '#152238' },
  { label: 'Sport Graphite', value: '#3F3F3F' },
  { label: 'Sport Graphite/White', value: '#3F3F3F' },
  { label: 'Sport Grey', value: '#9EA0A1' },
  { label: 'Sport Red', value: '#C8102E' },
  { label: 'Sport Royal/White', value: '#4169E1' },
  { label: 'Sport Scarlet Red/White', value: '#B82132' },
  { label: 'Sports Grey/Navy', value: '#9EA0A1' },
  { label: 'Sports Grey/Red', value: '#9EA0A1' },
  { label: 'Stone', value: '#928E85' },
  { label: 'Stonewash Denim', value: '#6F8FAF' },
  { label: 'Storm', value: '#4F5D75' },
  { label: 'Storm Camo', value: '#5C6B5C' },
  { label: 'Sunset', value: '#FAD6A5' },
  { label: 'Tahiti Blue', value: '#0F8FAB' },
  { label: 'Tropical Blue', value: '#3CB4E5' },
  { label: 'True Navy', value: '#1B264F' },
  { label: 'True Royal', value: '#2A4FB8' },
  { label: 'True Royal Triblend', value: '#2A4FB8' },
  { label: 'Turquoise', value: '#40E0D0' },
  { label: 'Vibrant Yellow', value: '#FFD500' },
  { label: 'Vintage Black', value: '#2B2B2B' },
  { label: 'Vintage Camel', value: '#B58F58' },
  { label: 'Vintage Denim', value: '#6F8FAF' },
  { label: 'Vintage Navy', value: '#28344E' },
  { label: 'Vintage Pink', value: '#E8B5B5' },
  { label: 'Vintage Red', value: '#A8323A' },
  { label: 'Vintage Royal', value: '#3A55A8' },
  { label: 'Vintage Smoke', value: '#6A6A6A' },
  { label: 'Vintage White', value: '#F5F0E5' },
  { label: 'Vintage Zinc', value: '#7E7E7A' },
  { label: 'Walnut', value: '#5C4033' },
  { label: 'Watermelon/White', value: '#FC6C85' },
  { label: 'White', value: '#FFFFFF' },
  { label: 'White / Black', value: '#FFFFFF' },
  { label: 'White / Black Print', value: '#FFFFFF' },
  { label: 'White / Cobalt Blue', value: '#FFFFFF' },
  { label: 'White / Gradient', value: '#FFFFFF' },
  { label: 'White / Gradient Stacked', value: '#FFFFFF' },
  { label: 'White / Red', value: '#FFFFFF' },
  { label: 'White / Red White', value: '#FFFFFF' },
  { label: 'White / Red White Stacked', value: '#FFFFFF' },
  { label: 'White Heather', value: '#F0F0F0' },
  { label: 'White heather', value: '#F0F0F0' },
  { label: 'White Smoke', value: '#F5F5F5' },
  { label: 'White/Black', value: '#FFFFFF' },
  { label: 'White/Navy', value: '#FFFFFF' },
  { label: 'White/Red', value: '#FFFFFF' },
];

export function getColorHex(label: string): string | undefined {
  const normalised = label.toLowerCase().trim();
  return colorsMap.find((c) => c.label.toLowerCase().trim() === normalised)
    ?.value;
}

// Remove stale module.exports
